### ISSUE TITLE
section `typeIconOrPreviewImage` / branch compat9

### ISSUE THREAD

**Issue by DavidBruchmann** [teaminmedias-pluswerk/ke_search#241]
in TYPO3 v9 this section throws an error:
```
<f:section name="typeIconOrPreviewImage">
    <f:if condition="{icon} && !{preview}">
        <f:then>
            <f:image src="{icon}" maxWidth="16" maxHeight="16" />
        </f:then>
        <f:else>
            <f:image src="{preview}" treatIdAsReference="1" maxWidth="200" />
        </f:else>
    </f:if>
</f:section>
```
`{iconConf}` and `{preview}` both have been `null` in my case but in `src` was the icon-path to the file in the extension.

**Comment by DavidBruchmann** [comment]
Can be changed to this code, then it's working so far that no error-message is raised:
```
<f:section name="typeIconOrPreviewImage">
    <f:if condition="{iconConf} && !{preview}">
        <f:then>
            <f:image src="{icon}" maxWidth="16" maxHeight="16" />
        </f:then>
        <f:else>
            <f:if condition="{preview}">
            <f:image src="{preview}" treatIdAsReference="1" maxWidth="200" />
            </f:if>
        </f:else>
    </f:if>
</f:section>
```
But I remarked the preview never seems being available anymore, the variable is always NULL

**Comment by kiefer79** [comment]
@DavidBruchmann 
I wasn't able to reproduce this bug, but I pushed your code to `compat9`. Could you please check if it's OK now and close the issue? Thanks.

**Comment by DavidBruchmann** [comment]
Yes, thanks, the fluid-template is ok now.
The question why the {preview} aka {resultrow.previewReferenceUid} is not created is still open, shall I create a new issue for that or does it depend on some setting I missed?

**Comment by kiefer79** [comment]
You're right. Leave the issue open. I'll have a deeper look into it when other - more important - issues of the v3 milestone are closed.

**Comment by DavidBruchmann** [comment]
Here I still have some debug-output, just to show some configuration too.
![image](https://user-images.githubusercontent.com/999146/50213397-1c927b00-03b0-11e9-98a5-b3442bbfa50d.png)
Debug comand was always appended to the lines, so line-numbers keep the same.

**Comment by christianbltr** [comment]
@DavidBruchmann Could you create a new issue for https://github.com/teaminmedias-pluswerk/ke_search/issues/241#issuecomment-448532271?
I would like to clean up the issue tracker a bit and I think it would be easier to understand the issue later on if we treat it as a separate one.

**Comment by christianbltr** [comment]
I opened up #261 for that @DavidBruchmann
